# Generated by Django 4.0.4 on 2022-06-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='formato',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Formato'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal6.autor', verbose_name='Quem Escreveu'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_lancamento',
            field=models.DateField(verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal6.formato'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=255, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='numero_paginas',
            field=models.PositiveIntegerField(verbose_name='Número de Páginas'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
