# Generated by Django 4.0.4 on 2022-06-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal6', '0002_alter_editora_estado_alter_formato_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, verbose_name='País')),
            ],
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='formato',
            options={'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255, verbose_name='Estado ou DF')),
                ('state_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal6.country', verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='Cidade')),
                ('city_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal6.state', verbose_name='Estado ou DF')),
            ],
        ),
    ]
